apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharding
  labels:
    app: sharding
spec:
  serviceName: sharding
  replicas: 2
  selector:
    matchLabels:
      app: sharding
  template:
    metadata:
      labels:
        app: sharding
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: sharding
        image: hesslee/sharding
        imagePullPolicy: Always
        command:
        - tail
        - "-f"
        - /dev/null
        ports:
        - containerPort: 20300
          protocol: TCP
        volumeMounts:
        - name: sharding-data-dbs
          mountPath: /home/altibase/altibase_home/dbs
        - name: sharding-data-logs
          mountPath: /home/altibase/altibase_home/logs
        - name: sharding-data-xlogs
          mountPath: /home/altibase/altibase_home/xlogs
        - name: sharding-data-arch-logs
          mountPath: /home/altibase/altibase_home/arch_logs
        - name: sharding-data-trc
          mountPath: /home/altibase/altibase_home/trc
  volumeClaimTemplates:
  - metadata:
      name: sharding-data-dbs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: sharding-storage
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sharding-data-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: sharding-storage
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sharding-data-xlogs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: sharding-storage
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sharding-data-arch-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: sharding-storage
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sharding-data-trc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: sharding-storage
      resources:
        requests:
          storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  sharding-storage
provisioner: k8s.io/minikube-hostpath
