apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sd
  labels:
    app: sd
spec:
  serviceName: sd
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: sd
  template:
    metadata:
      labels:
        app: sd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - sd
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: sd
        image: hesslee/sharding
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "2"
        command:
        #- tail
        #- "-f"
        #- /dev/null
        - /bin/bash
        - "-c"
        - /home/altibase/altibase_home/config_map/entry_point.sh
        ports:
        - containerPort: 20300
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 4
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 4
        volumeMounts:
        - name: sd-dbs
          mountPath: /home/altibase/altibase_home/dbs
        - name: sd-logs
          mountPath: /home/altibase/altibase_home/logs
        - name: sd-xlogs
          mountPath: /home/altibase/altibase_home/xlogs
        - name: sd-archlogs
          mountPath: /home/altibase/altibase_home/arch_logs
        - name: sd-trc
          mountPath: /home/altibase/altibase_home/trc
        - name: sd-cm
          mountPath: /home/altibase/altibase_home/config_map
          readOnly: true
        - name: zk-cm
          mountPath: /home/altibase/altibase_home/ZookeeperServer/config_map
          readOnly: true
      volumes:
        - name: sd-cm
          configMap:
            name: sd-cm
            defaultMode: 0777
            items:
            - key: "set_altibase.env"
              path: "set_altibase.env"
            - key: "base_schema.sql"
              path: "base_schema.sql"
            - key: "entry_point.sh"
              path: "entry_point.sh"
        - name: zk-cm
          configMap:
            name: zk-cm
            defaultMode: 0777
            items:
            - key: "zoo.cfg"
              path: "zoo.cfg"
  volumeClaimTemplates:
  - metadata:
      name: sd-dbs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sd-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sd-xlogs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: sd-archlogs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: sd-trc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi

