apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharding
  labels:
    app: sharding
spec:
  serviceName: sharding
  replicas: 2
  selector:
    matchLabels:
      app: sharding
  template:
    metadata:
      labels:
        app: sharding
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - sharding
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: sharding
        image: hesslee/sharding
        imagePullPolicy: Always
        command:
        #- tail
        #- "-f"
        #- /dev/null
        - /bin/bash
        - "-c"
        - /home/altibase/altibase_home/config_map/entry_point.sh
        ports:
        - containerPort: 20300
          protocol: TCP
        volumeMounts:
        - name: sharding-data-dbs
          mountPath: /home/altibase/altibase_home/dbs
        - name: sharding-data-logs
          mountPath: /home/altibase/altibase_home/logs
        - name: sharding-data-xlogs
          mountPath: /home/altibase/altibase_home/xlogs
        - name: sharding-data-archlogs
          mountPath: /home/altibase/altibase_home/arch_logs
        - name: sharding-data-trc
          mountPath: /home/altibase/altibase_home/trc
        - name: config
          mountPath: /home/altibase/altibase_home/config_map
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: sharding-config
            defaultMode: 0777
            items:
            - key: "set_altibase.env"
              path: "set_altibase.env"
            - key: "base_schema.sql"
              path: "base_schema.sql"
            - key: "entry_point.sh"
              path: "entry_point.sh"
  volumeClaimTemplates:
  - metadata:
      name: sharding-data-dbs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sharding-data-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sharding-data-xlogs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: sharding-data-archlogs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: sharding-data-trc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi

