apiVersion: v1
kind: ConfigMap
metadata:
  name: sharding-config
data:
  set_altibase.env: |
    export ALTIBASE_HOME=/home/altibase/altibase_home
    export ALTIBASE_NLS_USE=UTF8
    export ALTIBASE_PORT_NO=20300
    export DB_INITSIZE=10 #init Memory DB Size (Mbyte)
    export DB_CHARSET=UTF8
    export DB_NATIONAL_CHARSET=UTF8
    export SYS_USER_ID=sys
    export SYS_USER_PASSWD=manager
    # DB_ARCH_MODE: "NOARCHIVELOG" or "ARCHIVELOG"
    export DB_ARCH_MODE="NOARCHIVELOG"
    export PATH=${ALTIBASE_HOME}/bin:${PATH}
    export LD_LIBRARY_PATH=${ALTIBASE_HOME}/lib:${LD_LIBRARY_PATH};
    export CLASSPATH=${ALTIBASE_HOME}/lib/Altibase.jar:${CLASSPATH};
    
  base_schema.sql: |
    drop table t1 cascade;
    drop table _bak_t1 cascade;
    create table t1(c1 int);
    
  entry_point.sh: |
    #!/bin/bash
    . /home/altibase/altibase_home/config_map/set_altibase.env
    function db_create()
    {
        if [[ ! -f "${ALTIBASE_HOME}/dbs/system001.dbf" ]]
        then
            ADMIN="${ALTIBASE_HOME}/bin/isql -u ${SYS_USER_ID} -p ${SYS_USER_PASSWD} -sysdba -noprompt"
            ${ADMIN} << EOF
                startup process;
                CREATE DATABASE mydb INITSIZE=${DB_INITSIZE}M ${DB_ARCH_MODE} CHARACTER SET ${DB_CHARSET} NATIONAL CHARACTER SET ${DB_NATIONAL_CHARSET};
                shutdown abort;
                quit
    EOF
        fi
    }
 
    prepare_main()
    {
        db_create
        server start
        is -silent -u ${SYS_USER_ID} -p ${SYS_USER_PASSWD} -f ${ALTIBASE_HOME}/config_map/base_schema.sql
 
        tail -f /dev/null
    }
 
    prepare_main $@
