apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-cm
data:
  zoo.cfg: |
    clientPort=2181
    dataDir=/home/altibase/altibase_home/ZookeeperServer/data
    dataLogDir=/home/altibase/altibase_home/ZookeeperServer/log
    4lw.commands.whitelist=*
    tickTime=2000
    initLimit=10
    syncLimit=2000
    server.1=zk-0.zk-hs.default.svc.cluster.local:2888:3888
    server.2=zk-1.zk-hs.default.svc.cluster.local:2888:3888
    server.3=zk-2.zk-hs.default.svc.cluster.local:2888:3888

  zk-ready.sh: |
    OK=$(echo ruok | nc 127.0.0.1 $1)
    if [ "$OK" == "imok" ]; then
        exit 0
    else
        exit 1
    fi
    
  entry_point.sh: |
    #!/bin/bash
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.342.b07-1.el7_9.x86_64/jre
    export ALTIBASE_HOME=/home/altibase/altibase_home

    cp ${ALTIBASE_HOME}/ZookeeperServer/config_map/zoo.cfg ${ALTIBASE_HOME}/ZookeeperServer/conf/zoo.cfg

    idx=${HOSTNAME##*-}
    idxPlus=$(($idx + 1))
    echo ${idxPlus} > ${ALTIBASE_HOME}/ZookeeperServer/data/myid

    ${ALTIBASE_HOME}/ZookeeperServer/bin/zkServer.sh --config ${ALTIBASE_HOME}/ZookeeperServer/conf start

    tail -f /dev/null
