apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-cm
data:
  zoo.cfg: |
    clientPort=2181
    dataDir=/home/altibase/ZookeeperServer/data
    dataLogDir=/home/altibase/ZookeeperServer/log
    tickTime=2000
    initLimit=10
    syncLimit=2000
    server.1=zk-0.zk-hs.default.svc.cluster.local:2888:3888
    server.2=zk-1.zk-hs.default.svc.cluster.local:2888:3888
    server.3=zk-2.zk-hs.default.svc.cluster.local:2888:3888

  zookeeper-ready.sh: |
    OK=$(echo ruok | nc 127.0.0.1 $1)
    if [ "$OK" == "imok" ]; then
        exit 0
    else
        exit 1
    fi
    
  entry_point.sh: |
    #!/bin/bash
    cp /home/altibase/ZookeeperServer/config_map/zoo.cfg /home/altibase/ZookeeperServer/conf/zoo.cfg

    idx=${HONAME##*-}
    idxPlus=$(($idx + 1))
    echo ${idxplus} > /home/altibase/ZookeeperServer/data/myid
    
    tail -f /dev/null
