apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  labels:
    app: zk
spec:
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
    spec:
      affinity:
        # This part should be removed in production environment
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
        # This part should be uncommented in production environment
        #podAntiAffinity:
        #  requiredDuringSchedulingIgnoredDuringExecution:
        #    - labelSelector:
        #        matchExpressions:
        #          - key: "app"
        #            operator: In
        #            values:
        #            - zk
        #      topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zk
        image: hesslee/sharding
        imagePullPolicy: Always
        # This part need to be considered in production environment
        #resources:
        #  requests:
        #    memory: "100Mi"
        #    cpu: "2"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        #- tail
        #- "-f"
        #- /dev/null
        - /bin/bash
        - "-c"
        - /home/altibase/altibase_home/ZookeeperServer/config_map/entry_point.sh
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "/home/altibase/altibase_home/ZookeeperServer/config_map/zk-ready.sh 2181"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "/home/altibase/altibase_home/ZookeeperServer/config_map/zk-ready.sh 2181"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: zk-data
          mountPath: /home/altibase/altibase_home/ZookeeperServer/data
        - name: zk-log
          mountPath: /home/altibase/altibase_home/ZookeeperServer/log
        - name: zk-cm
          mountPath: /home/altibase/altibase_home/ZookeeperServer/config_map
          readOnly: true
      volumes:
        - name: zk-cm
          configMap:
            name: zk-cm
            defaultMode: 0777
            items:
            - key: "set.env"
              path: "set.env"
            - key: "zoo.cfg"
              path: "zoo.cfg"
            - key: "zk-ready.sh"
              path: "zk-ready.sh"
            - key: "entry_point.sh"
              path: "entry_point.sh"

  volumeClaimTemplates:
  - metadata:
      name: zk-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: zk-log
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi
