apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  labels:
    app: zk
spec:
  serviceName: zk-hs
  replicas: 3
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
    spec:
      affinity:
        # This part should be removed in production environment
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
        # This part should be uncommented in production environment
        #podAntiAffinity:
        #  requiredDuringSchedulingIgnoredDuringExecution:
        #    - labelSelector:
        #        matchExpressions:
        #          - key: "app"
        #            operator: In
        #            values:
        #            - zk
        #      topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zk
        image: hesslee/sharding
        imagePullPolicy: Always
        command:
        #- tail
        #- "-f"
        #- /dev/null
        - /bin/bash
        - "-c"
        - /home/altibase/altibase_home/config_map/entry_point.sh
        ports:
        - containerPort: 20300
          protocol: TCP
        volumeMounts:
        - name: sharding-data-zkdatadir
          mountPath: /home/altibase/altibase_home/ZookeeperServer/datadir

  volumeClaimTemplates:
  - metadata:
      name: sharding-data-zkdatadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi
