apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zookeeper
        image: hesslee/sharding
        imagePullPolicy: Always
        command:
        #- tail
        #- "-f"
        #- /dev/null
        - /bin/bash
        - "-c"
        - /home/altibase/altibase_home/config_map/entry_point.sh
        ports:
        - containerPort: 20300
          protocol: TCP
        volumeMounts:
        - name: sharding-data-zkdatadir
          mountPath: /home/altibase/altibase_home/ZookeeperServer/datadir

  volumeClaimTemplates:
  - metadata:
      name: sharding-data-zkdatadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: external-storage
      resources:
        requests:
          storage: 100Mi
